/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameMgr from "./game/GameMgr"
import AddCoinBtn from "./ui/AddCoinBtn"
import UIButton from "./ui/UIButton"
import BottomPanel from "./ui/BottomPanel"
import ShopToggle from "./ui/ShopPanel/ShopToggle"
import ShopItem from "./ui/ShopPanel/ShopItem"
import ShopList from "./ui/ShopPanel/ShopList"
import MyPanelTogle from "./ui/MyPanel/MyPanelTogle"
import RankToggle from "./ui/RankPanel/RankToggle"
import RankPanel from "./ui/RankPanel/RankPanel"
import RepairPanel from "./ui/RepairPanel/RepairPanel"
import LoadingPanel from "./ui/LoadingPanel/LoadingPanel"
import NetManager from "./game/NetManager"
// import TestList from "./../../../Program Files (x86)/LayaAirIDE (2)/resources/app/out/vs/layaEditor/src/TestList"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("game/GameMgr.js",GameMgr);
		reg("ui/AddCoinBtn.js",AddCoinBtn);
		reg("ui/UIButton.js",UIButton);
		reg("ui/BottomPanel.js",BottomPanel);
		reg("ui/ShopPanel/ShopToggle.js",ShopToggle);
		reg("ui/ShopPanel/ShopItem.js",ShopItem);
		reg("ui/ShopPanel/ShopList.js",ShopList);
		reg("ui/MyPanel/MyPanelTogle.js",MyPanelTogle);
		reg("ui/RankPanel/RankToggle.js",RankToggle);
		reg("ui/RankPanel/RankPanel.js",RankPanel);
		reg("ui/RepairPanel/RepairPanel.js",RepairPanel);
		reg("ui/LoadingPanel/LoadingPanel.js",LoadingPanel);
		reg("game/NetManager.js",NetManager);
		// reg("../../../Program Files (x86)/LayaAirIDE (2)/resources/app/out/vs/layaEditor/src/TestList.js",TestList);
    }
}
GameConfig.width = 750;
GameConfig.height = 1334;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "horizontal";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Main.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = true;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
